import { describe, it, expect } from 'vitest';
import { ModelGenerator } from '../src/model/index.js';
import type { SpecModel, GeneratorContext } from '@kodeai/core';

const ctx: GeneratorContext = {
  specsDir: 'specs',
  outputDir: 'src/generated',
  extensionsDir: 'src/extensions',
  allSpecs: [],
};

function makeSpec(overrides: Partial<SpecModel> = {}): SpecModel {
  return {
    model: 'Product',
    fields: {
      id: { type: 'uuid', primary: true },
      name: { type: 'string', min: 1, max: 200 },
      price: { type: 'decimal', precision: 10, scale: 2, min: 0 },
      stock: { type: 'integer', min: 0, default: 0 },
      active: { type: 'boolean', default: true },
    },
    timestamps: true,
    ...overrides,
  };
}

describe('ModelGenerator — types', () => {
  it('generates Product interface', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('export interface Product {');
    expect(types.content).toContain('id: string;');
    expect(types.content).toContain('name: string;');
    expect(types.content).toContain('price: number;');
    expect(types.content).toContain('stock: number;');
    expect(types.content).toContain('active: boolean;');
  });

  it('generates timestamps fields', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('createdAt: Date;');
    expect(types.content).toContain('updatedAt: Date;');
  });

  it('omits timestamps when disabled', async () => {
    const result = await ModelGenerator.generate([makeSpec({ timestamps: false })], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).not.toContain('createdAt');
    expect(types.content).not.toContain('updatedAt');
  });

  it('generates softDelete field', async () => {
    const result = await ModelGenerator.generate([makeSpec({ softDelete: true })], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('deletedAt: Date | null;');
  });

  it('generates CreateInput with optional defaults', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('export interface CreateProductInput {');
    expect(types.content).toContain('name: string;');
    expect(types.content).toContain('stock?: number;');
    expect(types.content).toContain('active?: boolean;');
  });

  it('generates UpdateInput with all optional', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('export interface UpdateProductInput {');
    expect(types.content).toContain('name?: string;');
    expect(types.content).toContain('price?: number;');
  });

  it('generates Response and ListResponse types', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('export interface ProductResponse {');
    expect(types.content).toContain('export interface ProductListResponse {');
    expect(types.content).toContain('data: Product;');
    expect(types.content).toContain('data: Product[];');
  });

  it('generates enum types as union', async () => {
    const spec = makeSpec({
      model: 'Task',
      fields: {
        id: { type: 'uuid', primary: true },
        status: { type: 'enum', values: ['pending', 'done', 'cancelled'] },
      },
    });
    const result = await ModelGenerator.generate([spec], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain("'pending' | 'done' | 'cancelled'");
  });

  it('generates FK field from belongsTo relation', async () => {
    const spec = makeSpec({
      model: 'Post',
      fields: { id: { type: 'uuid', primary: true }, title: { type: 'string' } },
      relations: { author: { type: 'belongsTo', model: 'User' } },
    });
    const result = await ModelGenerator.generate([spec], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('userId: string;');
  });

  it('generates auto-gen header', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const types = result.files.find((f) => f.path.includes('.types.ts'))!;
    expect(types.content).toContain('AUTO-GENERATED by Kodeai');
    expect(types.content).toContain('specs/models/product.spec.yaml');
  });
});

describe('ModelGenerator — schema', () => {
  it('generates pgTable with correct table name', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("pgTable('products'");
  });

  it('generates uuid primary key', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("uuid('id').defaultRandom().primaryKey()");
  });

  it('generates varchar with length', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("varchar('name', { length: 200 })");
  });

  it('generates decimal with precision/scale', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("decimal('price', { precision: 10, scale: 2 })");
  });

  it('generates notNull for required fields', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain(".notNull()");
  });

  it('generates default values', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain(".default(0)");
    expect(schema.content).toContain(".default(true)");
  });

  it('generates timestamps columns', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("timestamp('created_at').notNull().defaultNow()");
    expect(schema.content).toContain("timestamp('updated_at').notNull().defaultNow()");
  });

  it('generates unique constraint', async () => {
    const spec = makeSpec({
      fields: {
        id: { type: 'uuid', primary: true },
        email: { type: 'email', unique: true },
      },
    });
    const result = await ModelGenerator.generate([spec], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain('.unique()');
  });

  it('generates FK column from belongsTo', async () => {
    const spec = makeSpec({
      model: 'Post',
      fields: { id: { type: 'uuid', primary: true } },
      relations: { author: { type: 'belongsTo', model: 'User', foreignKey: 'authorId' } },
    });
    const result = await ModelGenerator.generate([spec], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("authorId: uuid('author_id').notNull()");
  });

  it('generates drizzle imports', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const schema = result.files.find((f) => f.path.includes('.schema.ts'))!;
    expect(schema.content).toContain("from 'drizzle-orm/pg-core'");
    expect(schema.content).toContain('pgTable');
    expect(schema.content).toContain('uuid');
    expect(schema.content).toContain('varchar');
    expect(schema.content).toContain('decimal');
    expect(schema.content).toContain('integer');
    expect(schema.content).toContain('boolean');
    expect(schema.content).toContain('timestamp');
  });

  it('generates index.ts re-exports', async () => {
    const result = await ModelGenerator.generate([makeSpec()], ctx);
    const index = result.files.find((f) => f.path.endsWith('models/index.ts'))!;
    expect(index.content).toContain("from './product.types.js'");
    expect(index.content).toContain("from './product.schema.js'");
  });
});
