/**
 * Naming conventions for Synap.
 */

export function toSnakeCase(str: string): string {
  return str.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

export function toKebabCase(str: string): string {
  return toSnakeCase(str).replace(/_/g, '-');
}

export function toTableName(model: string): string {
  const snake = toSnakeCase(model);
  return snake.endsWith('s') ? snake : snake + 's';
}

export function toCamelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

export function generatedHeader(source: string): string {
  const now = new Date().toISOString();
  return `/**
 * AUTO-GENERATED by Synap — Do not edit manually
 * Source: ${source}
 * Generated: ${now}
 */\n\n`;
}
